extends:
  - airbnb
  - airbnb/hooks
  - eslint:recommended
  - next/core-web-vitals
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/eslint-recommended
  - prettier
parser: '@typescript-eslint/parser'
plugins: [react, '@typescript-eslint']
root: true
rules:
  complexity: ['error', 10]
  max-depth: ['error', 2]
  max-lines: ['error', 250]
  max-nested-callbacks: ['error', 3]
