env:
  browser: true
  es6: true
  node: true
extends:
  - airbnb
  - airbnb/hooks
  - airbnb-typescript
  - eslint:recommended
  - next/core-web-vitals
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:react/recommended
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 13
  sourceType: module
  project: ./tsconfig.json
plugins: [react, '@typescript-eslint']
root: true
rules:
  complexity: ['error', 10]
  max-depth: ['error', 2]
  max-lines: ['error', 250]
  max-nested-callbacks: ['error', 3]
  react/function-component-definition: ['error', { namedComponents: 'arrow-function' }]
  react/react-in-jsx-scope: off
  semi: ['error', 'always']
